# Generate simulation data

```{r}
# /*===========================================================
#' # Preparation
# /*===========================================================
# === Packages ===#
library(data.table)
library(tidyverse)

# devtools::install_github("tmieno2/pasim")
library(pasim)
```

```{r}
# /*===========================================================
#' # Create a field
# /*===========================================================
# ! Define field and plot characteristics here

set.seed(278543)

sim_data <-
  gen_fields(
    plot_length = 12, # the length of a plot (in number of cells)
    plot_width = 3, # the width of a plot (in number of cells)
    cell_buffer = 1,
    aunit_length = 2, # the length of an analysis unit (in number of cells)
    aunit_width = 3, # the width of an analysis unit (in number of cells)
    cell = 6, # the length of a cell in meter
    #* how wide the field is
    # field_col = c(36, 72, 144), # the number of cell columns
    field_col = 144, # the number of cell columns
    #* how tall the field is
    field_row = 72 # the number of row columns
  ) %>%
  #--- add trial design layout ---#
  assign_trial_design(
    design = "Latin Square Fixed 5"
  ) %>%
  #--- generate true field parameters ---#
  mutate(field_pars = list(
    gen_field_parameters(
      field_sf,
      sp_range = 600,
      gstat_model = "Sph",
      nsim = 500
    )
  )) %>%
  #--- generate trial design ---#
  mutate(trial_design = list(
    gen_trial_design(field_sf, field_pars, design_name, num_treatments, Nk_minus = 40, Nk_plus = 20)
  )) %>%
  #--- generate regression data ---#
  mutate(reg_data = list(
    gen_analysis_data(field_pars, field_sf, field_au_sf, trial_design)
  )) %>%
  #--- create the weight matrix if necessary ---#
  mutate(weight_matrix = list(
    gen_weight_matrix(reg_data, cutoff = 50)
  ))

#* save the data
saveRDS(sim_data, here::here("Shared/Data/raw_sim_data.rds"))
```

# Save simulation data separately

```{r}
sim_data <-
  readRDS(here::here("Shared/Data/raw_sim_data.rds")) %>%
  data.table()

saveRDS(sim_data$weight_matrix[[1]], here::here("Shared/Data/weight_matrix.rds"))

saveRDS(sim_data$field_au_sf[[1]], here::here("Shared/Data/field_au_sf.rds"))

reg_data_all <- sim_data$reg_data[[1]]

lapply(
  1:nrow(reg_data_all),
  function(x) {
    saveRDS(
      reg_data_all[x, ],
      here::here(paste0("Shared/Data/SimData/sim_data_", reg_data_all[x, sim], ".rds"))
    )
  }
)
```
