---
title: "Summarize Results"
date: "2023-02-07"
output: html_document
---

# Objective 

+ Summarize the results

# Preparation

## Packages and functions 
```{r}
library(tidyverse)
library(pasim)
list.files(here::here("GitControlled/Codes/functions/"), full.names = TRUE) %>%
  lapply(., source)
```

## Parameters
```{r}
pCorn <- 6.25 / 25.4 # $/kg
pN <- 1 / 0.453592 # $/kg
```

## Data
```{r}
raw_data <- readRDS(here::here("Shared/Data/raw_sim_data.rds"))

#--- data for profit calculation ---#
all_reg_data <-
  raw_data$reg_data[[1]] %>%
  unnest(data) %>%
  data.table() %>%
  .[, .(sim, aunit_id, b0, b1, b2, Nk)]
```

# Whole-field analysis

## Combine the results and calcualte profit deficit

```{r}
results_whole <-
  list.files(
    here::here("Shared/Results/WholeField"),
    full.names = TRUE
  ) %>%
  purrr::map(readRDS) %>%
  rbindlist() %>%
  all_reg_data[., on = c("aunit_id", "sim")] %>%
  .[, yield_opt := gen_yield_QP(b0, b1, b2, Nk, opt_N)] %>%
  .[, yield_opt_hat := gen_yield_QP(b0, b1, b2, Nk, opt_N_hat)] %>%
  .[, pi_opt := pCorn * yield_opt - pN * opt_N] %>%
  .[, pi_opt_hat := pCorn * yield_opt_hat - pN * opt_N_hat] %>%
  .[, pi_deficit := pi_opt_hat - pi_opt] %>%
  .[order(sim), ]
```

## Summarize the results by sim and method

Find averate RMSE of EONR and $\pi_{deficit}$ and rank methods by sim based on RMSE of EONR.
```{r}
sum_results_whole <-
  results_whole %>%
  .[, N_dif := opt_N_hat - opt_N] %>%
  .[, .(
    rmse_eonr_true = sqrt(mean(N_dif^2)),
    pi_deficit = mean(pi_deficit)
  ), by = .(sim, method)] %>%
  #--- ranking of rmse eonr ---#
  .[order(sim, rmse_eonr_true), ] %>%
  .[, eonr_rank_true := seq(.N), by = sim] %>%
  .[, eonr_selected_true := ifelse(eonr_rank_true == 1, 1, 0)] %>%
  #--- ranking of profit deficit ---#
  .[order(sim, -pi_deficit), ] %>%
  .[, profit_rank_true := seq(.N), by = sim] %>%
  .[, profit_selected_true := ifelse(profit_rank_true == 1, 1, 0)]

# ggplot(sum_results_whole) +
#   geom_histogram(aes(x = rmse_eonr)) +
#   facet_grid(method ~ .)

# ggplot(sum_results_whole) +
#   geom_histogram(aes(x = pi_deficit)) +
#   facet_grid(method ~ .)

saveRDS(sum_results_whole, here::here("Shared/Results/sum_results_whole.rds"))
```

## Ranking visualization

```{r}
(
  g_true_rank_rmse_eonr <-
    sum_results_whole[, .(num_selected = sum(eonr_selected_true)), by = method] %>%
    ggplot(.) +
    geom_bar(aes(y = num_selected, x = method), stat = "identity")
)
```

# Model selection simulation results

```{r}
comp_results <-
  #--- specify the combination of num_folds and num_repeats ---#
  dplyr::tribble(
    ~num_folds, ~num_repeats,
    5, 1,
    7, 1,
    10, 1,
    5, 5,
    7, 5,
    10, 5,
    5, 10,
    7, 10,
    10, 10
  ) %>%
  rowwise() %>%
  mutate(comp_summary = list(
    process_model_selection_results(num_folds, num_repeats)
  )) %>%
  #--- create a table of selection performance based on local EONR prediction ---#
  mutate(selection_perf_rank_LE = list(
    comp_summary[eonr_selected_gam == 1, .N, by = eonr_rank_true] %>%
      .[order(eonr_rank_true), ] %>%
      .[, select_method := "Local EONR prediction"]
  )) %>%
  #--- create a table of selection performance based on yield prediction ---#
  mutate(selection_perf_rank_Y = list(
    comp_summary[yield_selected == 1, .N, by = eonr_rank_true] %>%
      .[order(eonr_rank_true), ] %>%
      .[, select_method := "Yield prediction"]
  )) %>%
  mutate(selection_perf = list(
    rbind(selection_perf_rank_LE, selection_perf_rank_Y) %>%
      dcast(eonr_rank_true ~ select_method, value.var = "N")
  )) %>%
  mutate(loss_data = list(
    find_loss_from_selection(comp_summary)
  ))

saveRDS(comp_results, here::here("Shared/Results/comp_results.rds"))
```



