
---
title: "Make figures and tables"
date: "2023-02-07"
output: html_document
---

# Preparation

## Set up a ggplot theme

```{r}
theme_fig <-
  theme_bw() +
  theme(
    axis.title.x =
      element_text(
        size = 7, angle = 0, hjust = .5, vjust = -0.3, family = "Helvetica"
      ),
    axis.title.y =
      element_text(
        size = 7, angle = 90, hjust = .5, vjust = .9, family = "Helvetica"
      ),
    axis.text.x =
      element_text(
        size = 7, angle = 0, hjust = .5, vjust = 1.5, family = "Helvetica"
      ),
    axis.text.y =
      element_text(
        size = 7, angle = 0, hjust = 1, vjust = 0, family = "Helvetica"
      ),
    axis.ticks =
      element_line(
        linewidth = 0.3, linetype = "solid"
      ),
    axis.ticks.length = unit(.15, "cm"),
    #--- legend ---#
    legend.text =
      element_text(
        size = 7, angle = 0, hjust = 0, vjust = 0.5, family = "Helvetica"
      ),
    legend.title =
      element_text(
        size = 7, angle = 0, hjust = 0, vjust = 0, family = "Helvetica"
      ),
    legend.key.size = unit(0.5, "cm"),
    #--- strip (for faceting) ---#
    strip.text = element_text(size = 7, family = "Helvetica"),
    #--- plot title ---#
    plot.title = element_text(family = "Helvetica", face = "bold", size = 7),
    #--- margin ---#
    # plot.margin = margin(0, 0, 0, 0, "cm"),
    #--- panel ---#
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(fill = NA)
  )
```

## Load results

```{r}
sum_results_whole <- readRDS(here::here("Shared/Results/sum_results_whole.rds"))

comp_results <-
  readRDS(here::here("Shared/Results/comp_results.rds")) %>%
  data.table()
```


# Performance of candidate models: true, yield-based, EONR-based

```{r}
true_rank <-
  sum_results_whole[, .(N = sum(eonr_selected_true)), by = method] %>%
  .[, type := "True"]

model_selection_ranks <-
  readRDS(here::here("Shared/Results/selection_ranks.rds")) %>%
  .[, .(N_LE = sum(eonr_selected_gam), N_Y = sum(yield_selected)), by = method] %>%
  melt(id.var = "method", value.name = "N") %>%
  .[, type := case_when(
    variable == "N_LE" ~ "Local EONR",
    variable == "N_Y" ~ "Yield"
  )] %>%
  .[, variable := NULL]

all_ranks <- rbind(true_rank, model_selection_ranks)

g_ranking <-
  ggplot(all_ranks) +
  geom_bar(
    aes(y = N, x = method, fill = type),
    stat = "identity",
    position = "dodge"
  ) +
  scale_fill_viridis_d() +
  # Add labels and titles
  labs(x = "Model", y = "Count", fill = "Selection Type") +
  theme_fig +
  theme(
    legend.position = "bottom"
  )
```

# Profit loss

```{r}
profit_loss_data <-
  comp_results[, .(num_folds, num_repeats, loss_data)] %>%
  unnest() %>%
  data.table() %>%
  .[, .(sim, num_folds, num_repeats, e_pi_loss, y_pi_loss)] %>%
  melt(id.var = c("sim", "num_folds", "num_repeats")) %>%
  .[, selection := case_when(
    variable == "e_pi_loss" ~ "LEONR-based Selection",
    variable == "y_pi_loss" ~ "Yield-based Selection"
  )]

g_pi_loss <-
  ggplot(profit_loss_data[num_folds == 5 & num_repeats == 5, ]) +
  geom_histogram(
    aes(x = value),
    color = "blue",
    fill = "white"
  ) +
  facet_wrap(selection ~ ., ncol = 1) +
  ylab("Count") +
  xlab("Profit Loss ($/acre)") +
  theme_bw()
```

